# Test consuming libbase122.
name: Test Consuming libbase122
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/cmake-build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build ${{github.workspace}}/cmake-build --config Debug

    - name: Install
      run: cmake --install ${{github.workspace}}/cmake-build --prefix ${{github.workspace}}/.install --config Debug

    - name: Consume with CMake config file
      working-directory: ${{github.workspace}}/test/testconsumer
      run: |
        cmake \
          -DLIBBASE122_USE_CONFIG_FILE=ON \
          -DLIBBASE122_USE_SHARED=ON \
          -DCMAKE_PREFIX_PATH=${{github.workspace}}/.install \
          -S. -Bcmake-build

        cmake --build cmake-build

        ./cmake-build/testconsumer
      
